update bins, base_image, docker make

diff --git a/bin/docker-enter b/bin/docker-enter
--- a/bin/docker-enter
+++ b/bin/docker-enter
@@ -1,9 +1,14 @@
 #!/bin/sh
 
-NSENTER=$(dirname "$0")/nsenter
+if [ -e $(dirname "$0")/nsenter ]; then
+    # with boot2docker, nsenter is not in the PATH but it is in the same folder
+    NSENTER=$(dirname "$0")/nsenter
+else
+    NSENTER=nsenter
+fi
 
 if [ -z "$1" ]; then
-    echo "Usage: docker-enter CONTAINER [COMMAND [ARG]...]"
+    echo "Usage: `basename "$0"` CONTAINER [COMMAND [ARG]...]"
     echo ""
     echo "Enters the Docker CONTAINER and executes the specified COMMAND."
     echo "If COMMAND is not specified, runs an interactive shell in CONTAINER."
@@ -16,14 +21,23 @@ else
 
     OPTS="--target $PID --mount --uts --ipc --net --pid --"
 
+    if [ "$(id -u)" -ne "0" ]; then
+        which sudo > /dev/null
+        if [ "$?" -eq "0" ]; then
+          LAZY_SUDO="sudo "
+        else
+          echo "Warning: Cannot find sudo; Invoking nsenter as the user $USER." >&2
+        fi
+    fi
+
     if [ -z "$1" ]; then
         # No command given.
         # Use su to clear all host environment variables except for TERM,
         # initialize the environment variables HOME, SHELL, USER, LOGNAME, PATH,
         # and start a login shell.
-        "$NSENTER" $OPTS su - root
+        $LAZY_SUDO "$NSENTER" $OPTS su - root
     else
         # Use env to clear all host environment variables.
-        "$NSENTER" $OPTS env --ignore-environment -- "$@"
+        $LAZY_SUDO "$NSENTER" $OPTS env --ignore-environment -- "$@"
     fi
 fi
